db:
  host: '192.168.1.229'
  port: 3306
  user: 'dev'
  password: 'Awesome85**'
  name: 'match'

cache:
  address: '192.168.1.229'
  port: ':6379'
  password: 'Awesome85**'
  db: 0
  pool_size: 25
  minimum_idle_connections: 10
  maximum_retries: 1
  token_key_format: 'token.%s'

consumer:
  brokers: ['192.168.1.229:9092']
  topic: 'delete.match.match'
  group_id: 'consumer.delete.match.group'

firebase:
  function_address: 'https://us-central1-superheromatch.cloudfunctions.net/deleteMatch'
  content_type: 'application/json'

health:
  port: ':8030'
  shutdown_endpoint: '/api/v1/consumer_match_delete_health/shutdown'
  content_type: 'application/json'