db:
  host: 'localhost'
  port: 3306
  user: 'root'
  password: 'Kolian18**'
  name: 'match'

consumer:
  brokers: ['192.168.178.17:9092']
  topic: 'delete.match.match'
  group_id: 'consumer-match-delete-group'